### ISSUE TITLE
由于统一认证升级 能否考虑升级该仓库代码？

### ISSUE THREAD

**Issue by pkmq24** [barryZZJ/CQU_crona_auto_report#1]
如题

**Comment by pkmq24** [comment]
https://github.com/Hagb/pymycqu/tree/dev

**Comment by barryZZJ** [comment]
好的，等我有时间了整一下，现在已经毕业了就是说。应该把我代码里的CquAuth魔改成你给的这个就行了

**Comment by barryZZJ** [comment]
不过就是改完了可能没法测试

**Comment by pkmq24** [comment]
谢了哥 我可以测试测试试试看

**Comment by barryZZJ** [comment]
推到 https://github.com/barryZZJ/CQU_crona_auto_report/tree/v2.0 了，你试试能行不

**Comment by pkmq24** [comment]
多谢，经验证可用
